name: Build and Test

on:
  pull_request:
  push:
    branches: [ "main" ]

jobs:

  test:
    runs-on: "ubuntu-22.04"
    steps:
    - uses: actions/checkout@v3

    - name: Set up Go
      uses: actions/setup-go@v3
      with:
        go-version: 1.21

    - name: Build
      run: go build -v ./...

    - name: Build LNURL Server
      run: go build -v
      working-directory: examples/lnurl-server
    
    - name: Build UMA Server
      run: go build -v
      working-directory: examples/uma-server
    
    - name: Build Remote Signing Server
      run: go build -v
      working-directory: examples/remote-signing-server

    - name: Test
      run: go test -v -tags='!integration' ./...

